### ISSUE TITLE
将config.yml写入到list.yml的内容，没有按照原顺序写入。

### ISSUE THREAD

**Issue by CHINAupup** [chengaopan/AutoMergePublicNodes#2]
导致list.yml不利于后期观察和编辑clash规则，规则顺序不对 也导致规则优先级混乱(特别是自定义规则)。

**Comment by chengaopan** [comment]
你好感谢你的建议  ,如果你有需要,可以fork之后自行修改一下或者你修改之后 可以提交一下pr

**Comment by peasoft** [comment]
原作者回复一下，这个问题在最新版中不存在。此 folk 已经长期未更新，请改用原版：<https://github.com/peasoft/NoMoreWalls>
@chengaopan
